// <auto-generated />
using System;
using ConferenceHallBooking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceHallBooking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904110327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HallId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.BookingOption", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceAtBooking")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId", "OptionId");

                    b.HasIndex("OptionId");

                    b.ToTable("BookingOptions");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.HallOption", b =>
                {
                    b.Property<Guid>("HallId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("HallId", "OptionId");

                    b.HasIndex("OptionId");

                    b.ToTable("HallOptions");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("ConferenceHallBooking.Domain.Entities.Hall", "Hall")
                        .WithMany("Bookings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.BookingOption", b =>
                {
                    b.HasOne("ConferenceHallBooking.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingOptions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceHallBooking.Domain.Entities.Option", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.HallOption", b =>
                {
                    b.HasOne("ConferenceHallBooking.Domain.Entities.Hall", "Hall")
                        .WithMany("HallOptions")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceHallBooking.Domain.Entities.Option", "Option")
                        .WithMany("HallOptions")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingOptions");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.Hall", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("HallOptions");
                });

            modelBuilder.Entity("ConferenceHallBooking.Domain.Entities.Option", b =>
                {
                    b.Navigation("HallOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
